insert into public.taxonomies (kind, label)
values
  ('type', 'Publicité'),
  ('type', 'Corpo'),
  ('type', 'Capsule'),
  ('type', 'Motion design'),
  ('type', 'Animation 3D'),
  ('type', 'Captation'),
  ('type', 'Événement'),
  ('type', 'Vidéoclip'),
  ('type', 'Beauty Shots'),
  ('type', 'GIF'),
  ('type', 'BTS'),
  ('type', 'Podcast'),
  ('type', 'Slideshow'),
  ('type', 'Court métrage'),
  ('type', 'Story'),
  ('type', 'Immobilier'),
  ('type', 'Documentaire'),
  ('keyword', 'Épicerie'),
  ('keyword', 'Acteur'),
  ('keyword', 'Communautaire'),
  ('keyword', 'Bar'),
  ('keyword', 'Nourriture'),
  ('keyword', 'Construction'),
  ('keyword', 'Commerce'),
  ('keyword', 'Noël'),
  ('keyword', 'Animation 2D et 3D'),
  ('keyword', 'Enfant'),
  ('keyword', 'Jouets'),
  ('keyword', 'Bière et vin'),
  ('keyword', 'Musique'),
  ('keyword', 'Restaurant'),
  ('keyword', 'Bureau'),
  ('keyword', 'Produit'),
  ('keyword', 'Café'),
  ('keyword', 'Gym'),
  ('keyword', 'Vêtements'),
  ('keyword', 'Hiver'),
  ('keyword', 'Bijoux'),
  ('keyword', 'Art'),
  ('keyword', 'École'),
  ('keyword', 'Technologie'),
  ('keyword', 'Santé'),
  ('keyword', 'Nature'),
  ('keyword', 'Sports'),
  ('keyword', 'Science'),
  ('keyword', 'Évènement'),
  ('keyword', 'Enfance'),
  ('keyword', 'Conférencier'),
  ('keyword', 'Montgolfière'),
  ('keyword', 'Festival'),
  ('keyword', 'Animateur'),
  ('keyword', 'Message Visuel'),
  ('keyword', 'Maladie et handicap'),
  ('keyword', 'Hôpital'),
  ('keyword', 'Conversation'),
  ('keyword', 'Ado'),
  ('keyword', 'Présentation'),
  ('keyword', 'Animaux'),
  ('keyword', 'Bateau'),
  ('keyword', 'Feu'),
  ('keyword', 'Golf'),
  ('keyword', 'Entrepôt'),
  ('keyword', 'Aînés'),
  ('keyword', 'Employés'),
  ('keyword', 'Mariage'),
  ('keyword', 'Danse'),
  ('style', 'Entrevue'),
  ('style', 'B-roll'),
  ('style', 'Épaule'),
  ('style', 'Stabilisateur'),
  ('style', 'Slider'),
  ('style', 'Drone'),
  ('style', 'Trépied'),
  ('style', 'POV'),
  ('style', 'Stock Footage'),
  ('style', 'Ralenti'),
  ('style', 'Vidéo portrait'),
  ('style', 'Photo Flash'),
  ('style', 'Motion Design'),
  ('style', 'Voix-off'),
  ('style', 'Icône'),
  ('style', 'Podcast'),
  ('style', 'Téléphone'),
  ('style', 'Verticale'),
  ('style', 'Photos'),
  ('style', 'Animation 3D'),
  ('style', 'Timelapse'),
  ('style', 'GoPro'),
  ('style', 'Green Screen'),
  ('style', 'Stop-motion'),
  ('style', 'Vox-Pop'),
  ('style', 'VFX'),
  ('feel', 'Humour'),
  ('feel', 'Sérieux'),
  ('feel', 'Dynamique'),
  ('feel', 'Informatif'),
  ('feel', 'Triste'),
  ('feel', 'Énergitique'),
  ('feel', 'Passion'),
  ('feel', 'Enjoué'),
  ('feel', 'Festif'),
  ('feel', 'Nostalgique'),
  ('feel', 'Grandiose'),
  ('feel', 'Majestueux'),
  ('feel', 'Émotif'),
  ('feel', 'Épique'),
  ('feel', 'Rassurant'),
  ('parametre', 'Voix off')
on conflict do nothing;
